package converter_db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CURRENCY_PAIR_ENTITY.
 */
public class CurrencyPairEntity {

    /** Not-null value. */
    private String pair;
    private Long id;
    private java.util.Date created_date;
    private java.util.Date date;
    private Integer rate;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CurrencyPairEntity() {
    }

    public CurrencyPairEntity(Long id) {
        this.id = id;
    }

    public CurrencyPairEntity(String pair, Long id, java.util.Date created_date, java.util.Date date, Integer rate) {
        this.pair = pair;
        this.id = id;
        this.created_date = created_date;
        this.date = date;
        this.rate = rate;
    }

    /** Not-null value. */
    public String getPair() {
        return pair;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPair(String pair) {
        this.pair = pair;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getCreated_date() {
        return created_date;
    }

    public void setCreated_date(java.util.Date created_date) {
        this.created_date = created_date;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Integer getRate() {
        return rate;
    }

    public void setRate(Integer rate) {
        this.rate = rate;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
