package converter_db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CURRENCY_ENTITY.
 */
public class CurrencyEntity {

    private String symbol;
    private String name;
    private String countryName;
    private Long numericCode;
    /** Not-null value. */
    private String code;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CurrencyEntity() {
    }

    public CurrencyEntity(Long numericCode) {
        this.numericCode = numericCode;
    }

    public CurrencyEntity(String symbol, String name, String countryName, Long numericCode, String code) {
        this.symbol = symbol;
        this.name = name;
        this.countryName = countryName;
        this.numericCode = numericCode;
        this.code = code;
    }

    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCountryName() {
        return countryName;
    }

    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    public Long getNumericCode() {
        return numericCode;
    }

    public void setNumericCode(Long numericCode) {
        this.numericCode = numericCode;
    }

    /** Not-null value. */
    public String getCode() {
        return code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCode(String code) {
        this.code = code;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
