package converter_db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table CURRENCY_ENTITY.
 */
public class CurrencyEntity {

    private String symbol;
    private String name;
    private String country_name;
    private Long numeric_code;
    /** Not-null value. */
    private String currency_code;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public CurrencyEntity() {
    }

    public CurrencyEntity(Long numeric_code) {
        this.numeric_code = numeric_code;
    }

    public CurrencyEntity(String symbol, String name, String country_name, Long numeric_code, String currency_code) {
        this.symbol = symbol;
        this.name = name;
        this.country_name = country_name;
        this.numeric_code = numeric_code;
        this.currency_code = currency_code;
    }

    public String getSymbol() {
        return symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCountry_name() {
        return country_name;
    }

    public void setCountry_name(String country_name) {
        this.country_name = country_name;
    }

    public Long getNumeric_code() {
        return numeric_code;
    }

    public void setNumeric_code(Long numeric_code) {
        this.numeric_code = numeric_code;
    }

    /** Not-null value. */
    public String getCurrency_code() {
        return currency_code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCurrency_code(String currency_code) {
        this.currency_code = currency_code;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
