package converter_db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import converter_db.CurrencyEntity;
import converter_db.ConversionEntity;
import converter_db.CurrencyPairEntity;

import converter_db.CurrencyEntityDao;
import converter_db.ConversionEntityDao;
import converter_db.CurrencyPairEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig currencyEntityDaoConfig;
    private final DaoConfig conversionEntityDaoConfig;
    private final DaoConfig currencyPairEntityDaoConfig;

    private final CurrencyEntityDao currencyEntityDao;
    private final ConversionEntityDao conversionEntityDao;
    private final CurrencyPairEntityDao currencyPairEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        currencyEntityDaoConfig = daoConfigMap.get(CurrencyEntityDao.class).clone();
        currencyEntityDaoConfig.initIdentityScope(type);

        conversionEntityDaoConfig = daoConfigMap.get(ConversionEntityDao.class).clone();
        conversionEntityDaoConfig.initIdentityScope(type);

        currencyPairEntityDaoConfig = daoConfigMap.get(CurrencyPairEntityDao.class).clone();
        currencyPairEntityDaoConfig.initIdentityScope(type);

        currencyEntityDao = new CurrencyEntityDao(currencyEntityDaoConfig, this);
        conversionEntityDao = new ConversionEntityDao(conversionEntityDaoConfig, this);
        currencyPairEntityDao = new CurrencyPairEntityDao(currencyPairEntityDaoConfig, this);

        registerDao(CurrencyEntity.class, currencyEntityDao);
        registerDao(ConversionEntity.class, conversionEntityDao);
        registerDao(CurrencyPairEntity.class, currencyPairEntityDao);
    }
    
    public void clear() {
        currencyEntityDaoConfig.getIdentityScope().clear();
        conversionEntityDaoConfig.getIdentityScope().clear();
        currencyPairEntityDaoConfig.getIdentityScope().clear();
    }

    public CurrencyEntityDao getCurrencyEntityDao() {
        return currencyEntityDao;
    }

    public ConversionEntityDao getConversionEntityDao() {
        return conversionEntityDao;
    }

    public CurrencyPairEntityDao getCurrencyPairEntityDao() {
        return currencyPairEntityDao;
    }

}
